site_name: ServiceComb Java Chassis 开发指南

nav:
- 入门: 
    - 术语表: 'start/terminology.md'
    - 微服务系统架构: 'start/architecture.md'
    - 安装本地开发环境: 'start/development-environment.md'
    - 开发第一个微服务: start/first-sample.md
    - 完整例子-porter应用: featured-topics/application-porter.md
- 开发服务提供者: 
    - 服务定义: build-provider/definition/service-definition.md
    - 定义服务契约: build-provider/define-contract.md
    - 使用隐式契约: build-provider/code-first.md
    - 使用Swagger注解: build-provider/swagger-annotation.md
    - 用SpringMVC开发微服务: build-provider/springmvc.md
    - 用JAX-RS开发微服务: build-provider/jaxrs.md
    - 用透明RPC开发微服务: build-provider/transparent-rpc.md
    - 接口定义和数据类型: build-provider/interface-constraints.md
    - 服务监听地址和发布地址: build-provider/listen-address-and-publish-address.md
    - 线程池: build-provider/thread-pool.md
    - 服务配置: 
        - 限流策略: build-provider/configuration/ratelimite-strategy.md
        - 降级策略: build-provider/configuration/downgrade-strategy.md
        - 参数效验: build-provider/configuration/parameter-validator.md
    - 程序启动逻辑: build-provider/bootup.md
    - Access Log配置: build-provider/access-log-configuration.md
- 开发服务消费者: 
    - 消费者通用配置项: build-consumer/common-configuration.md
    - 使用RestTemplate开发服务消费者: build-consumer/using-resttemplate.md
    - 使用AsynRestTemplate开发服务消费者: build-consumer/using-AsyncRestTemplate.md
    - 使用RPC方式开发服务消费者: build-consumer/develop-consumer-using-rpc.md
    - 使用服务契约: build-consumer/with-contract.md
    - 调用控制: 
        - 熔断策略: build-consumer/circuit-breaker.md
        - 限流策略: build-consumer/flow-control.md
        - 故障注入: build-consumer/fault-injection.md
    - 调用第三方REST服务: build-consumer/3rd-party-service-invoke.md
- Transports: 
    - REST over Servlet: transports/rest-over-servlet.md
    - REST over Vertx: transports/rest-over-vertx.md
    - Highway: transports/highway-rpc.md
    - HTTP2: transports/http2.md
- 通用开发: 
    - 访问服务中心: general-development/visit-sc.md
    - 应用性能监控: general-development/metrics.md
    - 微服务调用链: general-development/microservice-invocation-chain.md
    - 自定义调用链打点: general-development/customized-tracing.md
    - 本地开发和测试: general-development/local-develop-test.md
    - Http Filter: general-development/http-filter.md
    - 文件上传: general-development/file-upload.md
    - 文件下载: general-development/file-download.md
    - Reactive: general-development/reactive.md
    - DNS自定义配置: general-development/dnsconfig.md
    - 代理设置: general-development/dai-li-she-zhi.md
    - 框架上报版本号: general-development/report-framework-version.md
    - 跨应用调用: general-development/cross-app-invocation.md
    - 定制序列化和反序列化方法: general-development/secret-field.md
    - 使用Context传递控制消息: general-development/context.md
    - 返回值序列化扩展: general-development/produceprocess.md
    - CORS机制: general-development/CORS.md
    - 获取熔断与实例隔离告警事件信息: general-development/AlarmEvent.md
    - 优雅停机: general-development/shutdown.md
    - 异常处理: general-development/error-handling.md
    - 微服务实例间多环境隔离: general-development/multienvironment.md
    - 线程模型: general-development/thread-model.md
- 配置: 
    - 通用配置说明: config/general-config.md
    - 配置注入说明: config/inject-config.md
- 服务能力开放:
    - 介绍: edge/open-service.md
    - 使用Edge Service做边缘服务: edge/by-servicecomb-sdk.md
    - 使用confd和Nginx做边缘服务: edge/nginx.md
    - 使用zuul做边缘服务: edge/zuul.md
- 服务打包和运行: 
    - 以standalone模式打包: packaging/standalone.md
    - 以WEB容器模式打包: packaging/web-container.md
- 微服务安全: 
    - 使用TLS通信: security/tls.md
    - 使用RSA认证: security/shi-yong-rsa-ren-zheng.md
- 在Spring Boot中使用java chassis: 
    - 介绍: using-java-chassis-in-spring-boot/using-java-chassis-in-spring-boot.md
    - 提供的spring boot starter说明: using-java-chassis-in-spring-boot/components-for-spring-boot.md
    - JAVA应用方式开发步骤: using-java-chassis-in-spring-boot/java-application.md
    - Web开发方式开发步骤: using-java-chassis-in-spring-boot/web-application.md
    - Spring MVC开发习惯的差异: using-java-chassis-in-spring-boot/diff-spring-mvc.md
- 处理链参考: 
    - 处理链介绍: references-handlers/intruduction.md
    - 负载均衡: references-handlers/loadbalance.md
    - 公钥认证: references-handlers/publickey.md
- 1.x迁移2.x指南: upgrading/1_to_2.md
- 常见问题: 
    - 'Q & A' : question-and-answer/question_answer.md
    - 'FAQ' : question-and-answer/faq.md
    - 微服务接口兼容常见问题: question-and-answer/interface-compatibility.md

theme: readthedocs
plugins:
    - search:
          lang: en